### ISSUE TITLE
Replace abandoned raveren/kint package with kint-php/kint 

### ISSUE THREAD

**Issue by joeparsons** [az-digital/az-quickstart-dev#19]
## Problem/Motivation
The [raveren/kint](https://packagist.org/packages/raveren/kint) composer package is abandoned and no longer maintained. 

## Proposed resolution
The author suggests using the [kint-php/kint](https://packagist.org/packages/kint-php/kint) package instead.  kint-php/kint is also suggested by the devel maintainers.

**Comment by trackleft** [comment]
been meaning to do this
